// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// Training sessions or qualification rounds
type QualificationRound struct {
	ID uuid.UUID `json:"id"`
	// User ID from external authentication service (JWT claim: user_id or sub)
	ExternalUserID string             `json:"external_user_id"`
	RoundType      string             `json:"round_type"`
	Name           string             `json:"name"`
	Distance       int32              `json:"distance"`
	TotalSets      int32              `json:"total_sets"`
	ShotsPerSet    int32              `json:"shots_per_set"`
	TotalScore     int32              `json:"total_score"`
	AverageScore   pgtype.Numeric     `json:"average_score"`
	CompletedSets  int32              `json:"completed_sets"`
	StartTime      pgtype.Timestamptz `json:"start_time"`
	EndTime        pgtype.Timestamptz `json:"end_time"`
	Notes          pgtype.Text        `json:"notes"`
	TargetFaceID   uuid.UUID          `json:"target_face_id"`
	CompetitionID  pgtype.UUID        `json:"competition_id"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

// Series of shots (typically 3 or 6 arrows)
type Set struct {
	ID           uuid.UUID      `json:"id"`
	SetNumber    int32          `json:"set_number"`
	MaxShots     int32          `json:"max_shots"`
	TotalScore   int32          `json:"total_score"`
	AverageScore pgtype.Numeric `json:"average_score"`
	ShotsCount   int32          `json:"shots_count"`
	TenCount     int32          `json:"ten_count"`
	XCount       int32          `json:"x_count"`
	MissCount    int32          `json:"miss_count"`
	// Diameter of arrow grouping in mm (2 * standard deviation)
	GroupingDiameter pgtype.Numeric     `json:"grouping_diameter"`
	GroupingCenterX  pgtype.Numeric     `json:"grouping_center_x"`
	GroupingCenterY  pgtype.Numeric     `json:"grouping_center_y"`
	ParentRoundID    pgtype.UUID        `json:"parent_round_id"`
	ParentMatchID    pgtype.UUID        `json:"parent_match_id"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

// Individual shot records with coordinates and score
type Shot struct {
	ID uuid.UUID `json:"id"`
	// Horizontal offset from center in mm. Positive = right, Negative = left
	X pgtype.Numeric `json:"x"`
	// Vertical offset from center in mm. Positive = up, Negative = down
	Y                  pgtype.Numeric     `json:"y"`
	Score              int32              `json:"score"`
	DistanceFromCenter pgtype.Numeric     `json:"distance_from_center"`
	IsTen              bool               `json:"is_ten"`
	IsX                bool               `json:"is_x"`
	IsMiss             bool               `json:"is_miss"`
	Notes              pgtype.Text        `json:"notes"`
	SetID              uuid.UUID          `json:"set_id"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

// Target face configurations (WA 122cm, WA 80cm, etc.)
type TargetFace struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Standard        string             `json:"standard"`
	TotalDiameter   int32              `json:"total_diameter"`
	ScoringDiameter int32              `json:"scoring_diameter"`
	ZonesConfig     []byte             `json:"zones_config"`
	MaxScore        int32              `json:"max_score"`
	HasX            bool               `json:"has_x"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
