// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchCreateShots(ctx context.Context, arg BatchCreateShotsParams) ([]Shot, error)
	CreateQualificationRound(ctx context.Context, arg CreateQualificationRoundParams) (QualificationRound, error)
	CreateSet(ctx context.Context, arg CreateSetParams) (Set, error)
	CreateShot(ctx context.Context, arg CreateShotParams) (Shot, error)
	GetQualificationRound(ctx context.Context, id uuid.UUID) (QualificationRound, error)
	GetQualificationRoundsForUser(ctx context.Context, externalUserID string) ([]QualificationRound, error)
	GetSet(ctx context.Context, id uuid.UUID) (Set, error)
	GetSetsForQualificationRound(ctx context.Context, parentRoundID pgtype.UUID) ([]Set, error)
	GetShot(ctx context.Context, id uuid.UUID) (Shot, error)
	GetShotsBySet(ctx context.Context, setID uuid.UUID) ([]Shot, error)
}

var _ Querier = (*Queries)(nil)
