// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSet = `-- name: CreateSet :one
INSERT INTO sets (
    set_number,
    max_shots,
    parent_round_id
) VALUES ($1, $2, $3)
RETURNING id, set_number, max_shots, total_score, average_score, shots_count, ten_count, x_count, miss_count, grouping_diameter, grouping_center_x, grouping_center_y, parent_round_id, parent_match_id, created_at, updated_at, deleted_at
`

type CreateSetParams struct {
	SetNumber     int32       `json:"set_number"`
	MaxShots      int32       `json:"max_shots"`
	ParentRoundID pgtype.UUID `json:"parent_round_id"`
}

func (q *Queries) CreateSet(ctx context.Context, arg CreateSetParams) (Set, error) {
	row := q.db.QueryRow(ctx, createSet, arg.SetNumber, arg.MaxShots, arg.ParentRoundID)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.SetNumber,
		&i.MaxShots,
		&i.TotalScore,
		&i.AverageScore,
		&i.ShotsCount,
		&i.TenCount,
		&i.XCount,
		&i.MissCount,
		&i.GroupingDiameter,
		&i.GroupingCenterX,
		&i.GroupingCenterY,
		&i.ParentRoundID,
		&i.ParentMatchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSet = `-- name: GetSet :one
SELECT id, set_number, max_shots, total_score, average_score, shots_count, ten_count, x_count, miss_count, grouping_diameter, grouping_center_x, grouping_center_y, parent_round_id, parent_match_id, created_at, updated_at, deleted_at FROM sets WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSet(ctx context.Context, id uuid.UUID) (Set, error) {
	row := q.db.QueryRow(ctx, getSet, id)
	var i Set
	err := row.Scan(
		&i.ID,
		&i.SetNumber,
		&i.MaxShots,
		&i.TotalScore,
		&i.AverageScore,
		&i.ShotsCount,
		&i.TenCount,
		&i.XCount,
		&i.MissCount,
		&i.GroupingDiameter,
		&i.GroupingCenterX,
		&i.GroupingCenterY,
		&i.ParentRoundID,
		&i.ParentMatchID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSetsForQualificationRound = `-- name: GetSetsForQualificationRound :many
SELECT id, set_number, max_shots, total_score, average_score, shots_count, ten_count, x_count, miss_count, grouping_diameter, grouping_center_x, grouping_center_y, parent_round_id, parent_match_id, created_at, updated_at, deleted_at FROM sets WHERE parent_round_id = $1 AND deleted_at IS NULL ORDER BY set_number
`

func (q *Queries) GetSetsForQualificationRound(ctx context.Context, parentRoundID pgtype.UUID) ([]Set, error) {
	rows, err := q.db.Query(ctx, getSetsForQualificationRound, parentRoundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Set{}
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.ID,
			&i.SetNumber,
			&i.MaxShots,
			&i.TotalScore,
			&i.AverageScore,
			&i.ShotsCount,
			&i.TenCount,
			&i.XCount,
			&i.MissCount,
			&i.GroupingDiameter,
			&i.GroupingCenterX,
			&i.GroupingCenterY,
			&i.ParentRoundID,
			&i.ParentMatchID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
